language: python

services:
  - docker

before_install:
  - pip install poetry
install:
  - poetry install
script:
  # - poetry run black androgee/* --check
  # - poetry run flake8

after_success:
  - docker build -t egeeio/androgee .
  - docker login -u $username -p $pass

deploy:
  provider: script
  script: docker push egeeio/androgee
  on:
    branch: main
