language: python

services:
  - docker

before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8
  - poetry run mypy . --no-strict-optional --ignore-missing-imports --namespace-packages

after_success:
  - docker build -t egeeio/androgee .
  - echo "$pass" | docker login --username "$login" --password-stdin

deploy:
  provider: script
  script: docker push egeeio/androgee:latest
  on:
    branch: main
